spring:
  application:
    name: booklist
  datasource:
    url: jdbc:postgresql://localhost:5432/booklist
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jooq:
    sql-dialect: POSTGRES
