spring:
  application:
    name: booklist
  datasource:
    url: jdbc:postgresql://localhost:5432/booklist
    username: book_user
    password: book_user
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10